Document: snow2-client
Title: Debian snow2-client Manual
Author: <insert document author here>
Abstract: This manual describes what snow2-client is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/snow2-client/snow2-client.sgml.gz

Format: postscript
Files: /usr/share/doc/snow2-client/snow2-client.ps.gz

Format: text
Files: /usr/share/doc/snow2-client/snow2-client.text.gz

Format: HTML
Index: /usr/share/doc/snow2-client/html/index.html
Files: /usr/share/doc/snow2-client/html/*.html
